/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package B8;
import java.util.ArrayList;

/*
 * DO NOT EDIT THIS FILE
 */
public interface ICake {   
    /*
     * return the name of Cake which has highest sales price
     */
    public String getHighestPrice(ArrayList a);        
    /*
     * Count and return the number of the Cake that have imported tax  
     * less than the imported tax of the first Cake in the list
     */
    public int count(ArrayList a);
}
